### ISSUE TITLE
Add support for merge and archive options

### ISSUE THREAD

**Issue by SachaCR** [aidmax/structurizr-cli-action#16]
Hello,

Thanks for this very useful Github action. 
Do you think it's possible to support the two missing CLI options `merge` and `archive`?

I'm in a situation where my layout is not updated in the cloud when I push because the merge is by default true I guess.
I don't want to create a fork for this so here is the code just in case: 

```yml
  merge:
    description: 'Whether to merge layout information from the remote workspace (optional: defaults to true)'
    required: false
  archive:
    description: 'Whether to store the previous version of the remote workspace (optional; default to true)'
    required: false

...

    - '-merge'
    - ${{ inputs.merge }}
    - '-archive'
    - ${{ inputs.archive }}
```
